### PR TITLE
Added code to compute insertion indices

### PR DESCRIPTION
**Pull request by williamjameshandley**
# Description

This pull request implements some of the code that underpins https://arxiv.org/abs/2006.03371 

@andrewfowlie will likely have an opinion on which other pieces of code from
that paper are sufficiently general to make it into this paper

# Checklist:

- [X] I have performed a self-review of my own code
- [X] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [X] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [X] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by andrewfowlie** [comment]
I think this is quite nice. So you give the user access to the insertion indexes, then it's up to them how they do the tests on them? Should we also add a method for a user to perform the test?

**Comment by williamjameshandley** [comment]
I think it would be good to at least provide a function that computes the 'p value' and 'rolling p value' in `anesthetic.utils` as they were determined in `https://arxiv.org/abs/2006.03371`. You know that code best: would you be able to extract the relevant parts, paste it here, and I'll interface it appropriately to `NestedSamples`

**Comment by andrewfowlie** [comment]
```
import numpy as np
from scipy.stats import kstwobign


def p_value(indexes, n_live, iterations=None):
    """
    @returns Kolmogorov-Smirnov test from indexes

    Don't use scipy.stats.kstest as it assumes continuous distributions
    """
    if iterations is not None:
        indexes = indexes[:iterations]

    empirical_pmf = np.histogram(indexes, bins=np.arange(-0.5, n_live + 0.5, 1.), density=True)[0]
    empirical_cmf = np.cumsum(empirical_pmf)
    uniform_cmf = np.arange(1., n_live + 1., 1.) / n_live

    D = abs(empirical_cmf - uniform_cmf).max()
    sample_size = len(indexes)
    K = D * np.sqrt(sample_size)

    r = {}
    r["D"] = D
    r["sample_size"] = sample_size
    r["p_value_asymptotic"] = kstwobign.sf(K)
    return r

def rolling_p_value(indexes, n_live, iterations=None, chunk_k=1):
    """
    @returns Rolling Kolmogorov-Smirnov test from indexes
    """
    if iterations is not None:
        indexes = indexes[:iterations]

    sample_size = len(indexes)
    chunk_size = chunk_k * n_live
    chunks = [indexes[i:i + chunk_size] for i in range(0, len(indexes), chunk_size)]
    tests = [ks_ns(c, n_live) for c in chunks]
    test = min(tests, key=lambda t: t["p_value_asymptotic"])
    index = tests.index(test)
    test["iterations"] = (index * chunk_size, (index + 1) * chunk_size)
    test["n_chunks"] = len(chunks)
    test["p_value_uncorrected"] = test["p_value_asymptotic"]
    test["p_value_asymptotic"] = 1. - (1. - test["p_value_uncorrected"])**test["n_chunks"]
    if test["p_value_asymptotic"] == 0.:
        test["p_value_asymptotic"] = test["p_value_uncorrected"] * test["n_chunks"]
    return test
```

**Comment by williamjameshandley** [comment]
OK, I have added a version of that code as `anesthetic.utils.insertion_p_value`, and some tests to both validate, and show users how it works. Whilst the theory is still evolving (e.g. how to deal with a variable number of live points, how to correct properly for the initial and final live points), I will hold off from making a dedicated `NestedSamples` p-value checking function beyond the `NestedSamples._compute_insertion_indexes`, but I think it is very helpful to provide users with a p-value test that is appropriate for discrete uniform distributions.

**Comment by williamjameshandley** [comment]
If you're happy with this @andrewfowlie, could you approve again, and I will merge once the tests pass.

**Pull request merged**
