### PR TITLE
add `flake8` `pre-commit`

### PR DESCRIPTION
**Pull request by Ormorod**
I've lost count of how many times I've forgotten to `$ flake8 anesthetic tests`. This PR adds `.pre-commit-config.yaml` to help ameliorate this.

When `anesthetic` is cloned, the user should run:
```
pip install pre-commit flake8
pre-commit install
```

And this will prevent their changes from being committed without `flake8` compliance.

Screenshot 2023-02-10 at 20 10 02

**TL;DR**: this change requires `pre-commit install` to make any difference to a user.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [x] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [x] Add to documentation
- [x] Only check anesthetic and tests folders

### CODE REVIEW

**Comment by williamjameshandley** [comment]
This is quite a nifty idea, but my concern is that this would add friction and discourage (particularly new) developers from using version control, since in the early stages of mocking up some code flake8 compliance might slow people down.

Another option is a `pre-push` flake8, but again this would act to discourage users from backing up/switching machines.

Does it need to be committed to the repository, or could this just be added as a recommendation to developers? (there is after all nothing stopping individual users from adding this file).

**Comment by Ormorod** [comment]
Creating the file is something of a faff, it took me a few goes to get it working with a locally installed version of `flake8`, rather than linking it to a specific release sourced from github or gitlab. I still need to work out how to get it only to apply to `anesthetic/` and `tests/` like in the CI. At the moment it checks only files which have changed.

It doesn't add any friction to new devs; if `pre-commit install` isn't run after cloning the repo, then one can happily commit away without worrying about flake compliance, even if they have pre-commit pip installed.

e.g. after adding a line far too long:

Screenshot 2023-02-11 at 17 53 22

**Review by williamjameshandley — CHANGES_REQUESTED** [review]
OK then, if it really is opt-in, then this does indeed sound like a good addition.

Could we add the other CI checks (e.g. numpydoc etc)?

To flag this functionality to users, could you put a 'developers tools ' section in the `.github/CONTRIBUTING.md`?



P.S. where possible, please copy-paste CLI text, rather than screenshots -- it's useful to be able to quote/see in plain text emails.

**Comment by Ormorod** [comment]
> P.S. where possible, please copy-paste CLI text, rather than screenshots -- it's useful to be able to quote/see in plain text emails.

I just wanted to show how red and angry gets (or doesn't) to remind you to

**Comment by Ormorod** [comment]
> Could we add the other CI checks (e.g. numpydoc etc)?
> 
Yes, though I will need to take a moment to familiarise myself.

> To flag this functionality to users, could you put a 'developers tools ' section in the `.github/CONTRIBUTING.md`?
>
On it.

> P.S. where possible, please copy-paste CLI text, rather than screenshots -- it's useful to be able to quote/see in plain text emails.

I just wanted to show how usefully angry and red it looks when you try commit something linty

**Comment by Ormorod** [comment]
Pleeeeeeeeeeeeease can we get this one through so I (and hopefully we) can stop committing lint everywhere

**Review by lukashergt — APPROVED** [review]
> Pleeeeeeeeeeeeease can we get this one through so I (and hopefully we) can stop committing lint everywhere

Apologies, I wasn't aware this  was awaiting review. I think `flake8` and `pydocstyle` are the useful (quick) ones to catch with this.

Please feel free to squash and merge.

**Comment by lukashergt** [comment]
Oooh wow, ok, "requesting changes" requires the same reviewer to approve the changes... Sorry @Ormorod, can't help you here.

**Review by williamjameshandley — APPROVED** [review]

**Pull request merged**
