### PR TITLE
Conda CI AreaPlot issue

### PR DESCRIPTION
**Pull request by Ormorod**
# Description

The conda install CI finds an issue where one of the y limits of an `AreaPlot` is not zero for a `WeightedDataFrame`.

Solving this has proven difficult enough I think it deserves its own PR.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [ ] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [ ] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ormorod** [comment]
reverted to see what happens

**Comment by Ormorod** [comment]
As I understand it, the issue is that the area plots sometimes think the axes are being shared, so they don't adjust the y limits. 

The most recent tests look like this, using the format (axes_df, axes_wdf) where appropriate
| OS | python | is_shared_y | ylim |
|- |- |-| - |
| ubuntu | 3.8 | False, True | 0, -0.134755 | 
| ubuntu | 3.10 | False, False | 0, 0 |
| MacOS | 3.8 | True, True | -0.134755, -0.134755 |
| MacOS | 3.10 | True, True | -0.134755, -0.134755 |
| Windows | 3.8 | | |
| Windows | 3.10 | | |

I have also noticed that the axes_wdf has an xlabel of "None", hinting at possibly another issue

**Comment by Ormorod** [comment]
I've narrowed the problem down to two lines. In `test_BoxPlot()`, the plots created by grouping by `split` somehow sometimes survive, so that in `test_AreaPlot()` the y limit of 0 isn't applied. 

Can't say I know why this happens...

**Review by lukashergt — CHANGES_REQUESTED** [review]
> Edit: perhaps it would be good to make more use of the pandas plot testing structure? Rather than plt.close("all") all over the shop

I fear we won't get around  using `plt.close('all')`, and I do think that that might have been the issue, here... Not easy to spot, but on the upside, at least it is easy to fix :)

As suggested inline, let's revert everything except the missing `plt.close('all')` line.

**Comment by Ormorod** [comment]
> > Edit: perhaps it would be good to make more use of the pandas plot testing structure? Rather than plt.close("all") all over the shop
> 
> I fear we won't get around using `plt.close('all')`, and I do think that that might have been the issue, here... Not easy to spot, but on the upside, at least it is easy to fix :)
> 
> As suggested inline, let's revert everything except the missing `plt.close('all')` line.

I don't think this does fix it (but should be kept). The two lines I've commented out in `test_BoxPlot()` sometimes have side-effects on `test_AreaPlot()`, even with `plt.close("all")` added. Everything else is me exploring what is going on, and using the PR to test and record!

**Comment by Ormorod** [comment]
Double-checked `plt.close("all")` isn't enough

**Comment by lukashergt** [comment]
> Double-checked `plt.close("all")` isn't enough

That's a shame, but thanks for clarifying.

**Comment by lukashergt** [comment]
> I don't think this does fix it (but should be kept). The two lines I've commented out in `test_BoxPlot()` sometimes have side-effects on `test_AreaPlot()`, even with `plt.close("all")` added. Everything else is me exploring what is going on, and using the PR to test and record!

Hmm, weird. Maybe it has to do with the `group_by` functionality? Does that create some hidden plot that doesn't get closed and then interferes with `test_AreaPlot`?

**Comment by Ormorod** [comment]
I'll rerun these tests a few times, then remove the changes which are just to show the y limits of the `areaplot`s 

success 1/10

**Comment by Ormorod** [comment]
I don't think this worked after all :(

**Comment by williamjameshandley** [comment]
That is unbelievably frustrating...

Let's convene tomorrow morning in person to plan our strategy.

**Comment by Ormorod** [comment]
^ Last attempt for today

> That is unbelievably frustrating...
> 
> Let's convene tomorrow morning in person to plan our strategy.

I can do 9-9:45am or ≥3pm (rowing preseason...)

**Comment by Ormorod** [comment]
Dealt with in #248

**Pull request closed without merging**
